Repository BristolSTA/uobtheatre-web, pull requests merged in 2024-11, with the labels that each got.

#729 Fix ticket scanner stuck on loading screen
  components/ui/Input/UiInputTicketScanner.client.vue
Labels: bug, prio:high

#728 Add SameSite attribute to the auth cookies
  store/auth.ts
Labels: bug, prio:high

#744 Fix QR code scanner
  classes/Ticket.ts
  components/ui/Input/UiInputTicketScanner.client.vue
  composables/useHardwareTicketScanner.ts
  pages/box-office/[performanceId]/index.vue
  tests/unit/classes/Ticket.spec.js
Labels: bug, dependencies, prio:high

#565 feat: Maintenance banners to alert users of upcoming work
  components/layout/LayoutMaintenanceBanner.vue
  components/ui/UiStaButton.vue
  graphql/queries/AllSiteMessages.gql
  graphql/queries/UpcomingSiteMessages.gql
  layouts/default.vue
  tailwind.config.ts
  tests/unit/components/layout/MaintenanceBanner.spec.js
  tests/unit/components/production/ProductionBanner.spec.js
  tests/unit/components/production/ProductionCastCredits.spec.js
  tests/unit/components/production/ProductionDraftWarningBanner.spec.js
  tests/unit/support/fixtures/SiteMessage.js
Labels: enhancement, requires api change

#745 deps: 1.2.5 Dependency Bump
  package.json
  yarn.lock
Labels: dependencies
